### ISSUE TITLE
Problems with matterbridge-zigbee2mqtt.config.json on Docker installation

### ISSUE THREAD

**Issue by KC-inDomus** [Luligu/matterbridge-zigbee2mqtt#15]
Hi,
installed Matterbridge using docker with this configuration:

```
  matterbridge:
    container_name: matterbridge
    image: luligu/matterbridge:latest # Matterbridge image with the latest tag
    network_mode: host # Ensures the Matter mdns works
    restart: always # Ensures the container always restarts automatically
    volumes:
      - "${HOME}/Matterbridge:/root/Matterbridge" # Mounts the Matterbridge plugin directory
      - "${HOME}/.matterbridge:/root/.matterbridge" # Mounts the Matterbridge storage directory
```

It works. Then, I installed matterbridge-zigbee2mqtt plugin, restarted Matterbridge, and it works too.

Problems arise when trying to configure the plugin. I created a `matterbridge-zigbee2mqtt.config.json` file on the correct path (`${HOME}/.matterbridge`) with this contents:

```
{
  "name": "matterbridge-zigbee2mqtt",
  "type": "DynamicPlatform",
  "unregisterOnShutdown": false,
  "host": "192.168.1.98",
  "port": 1883,
  "topic": "zigbee2mqtt",
  "username": "mqtt_user",
  "password": "MY_PASSWORD",
  "whiteList": [],
  "blackList": []
}
```

The mqtt broker address, username and password are right.
When starting, matterbridge-zigbee2mqtt plugin gives:

`[08:50:59.846] [Zigbee2MQTT] Error connecting to mqtt://localhost:1883: Connection refused: Not authorized `

which suggests that config file hasn't be loaded.
After checking paths, contents and so on, I tried several time: every time he uses "localhost" - not the right configuration.
So I tried with:

`docker exec -it matterbridge sh`

and, in /`root/.matterbridge`, I found out the `matterbridge-zigbee2mqtt.config.json` which the plusin is using (despite my configuration), with this own contents:

```
{
  "name": "matterbridge-zigbee2mqtt",
  "type": "DynamicPlatform",
  "host": "localhost",
  "port": 1883,
  "topic": "zigbee2mqtt",
  "username": "",
  "password": "",
  "whiteList": [],
  "blackList": []
}
```

so I manually changed this configuration, saved the file, restarted the plugin... and again, "localhost" is used, because the file turns back to the original configuration as above.

No way to make the plugin use a different config.
KC
